export const CALLOUT_BACKGROUND_COLOR = {
  1: "lightred",
  2: "lightorange",
  3: "lightyellow",
  4: "lightgreen",
  5: "lightblue",
  6: "lightpurple",
  7: "lightgray",
  8: "darkred",
  9: "darkorange",
  10: "darkyellow",
  11: "darkgreen",
  12: "darkblue",
  13: "darkpurple",
  14: "darkgray",
};
